### ISSUE TITLE
Select interface

### ISSUE THREAD

**Issue by Allaux** [fazalfarhan01/EarnApp-Docker#14]
Hello,
Is possible to select interface because i have two interface in container : 
tun0 and eth0 and earnapp choise eth0 and not tun0

**Comment by fazalfarhan01** [comment]
@Allaux are the interfaces available inside the container?

**Comment by Allaux** [comment]
This is my log file:
`███████╗░█████╗░██████╗░███╗░░██╗░█████╗░██████╗░██████╗░  ██████╗░░█████╗░░█████╗░██╗░░██╗███████╗██████╗░
██╔════╝██╔══██╗██╔══██╗████╗░██║██╔══██╗██╔══██╗██╔══██╗  ██╔══██╗██╔══██╗██╔══██╗██║░██╔╝██╔════╝██╔══██╗
█████╗░░███████║██████╔╝██╔██╗██║███████║██████╔╝██████╔╝  ██║░░██║██║░░██║██║░░╚═╝█████═╝░█████╗░░██████╔╝
██╔══╝░░██╔══██║██╔══██╗██║╚████║██╔══██║██╔═══╝░██╔═══╝░  ██║░░██║██║░░██║██║░░██╗██╔═██╗░██╔══╝░░██╔══██╗
███████╗██║░░██║██║░░██║██║░╚███║██║░░██║██║░░░░░██║░░░░░  ██████╔╝╚█████╔╝╚█████╔╝██║░╚██╗███████╗██║░░██║
╚══════╝╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░╚══╝╚═╝░░╚═╝╚═╝░░░░░╚═╝░░░░░  ╚═════╝░░╚════╝░░╚════╝░╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝
An image by https://github.com/fazalfarhan01

Installing
✖ EarnApp was already started before.
2022-01-26 10:01:58.880 NOTICE: running PID: 25
2022-01-26 10:01:58.881 ERR: perr 05_svc_init {}
2022-01-26 10:01:58.883 ERR: perr init {}
2022-01-26 10:01:58.883 NOTICE: idle_state_monitor run
2022-01-26 10:01:58.886 NOTICE: run: E.start()
2022-01-26 10:01:58.887 NOTICE: devs changed: found 2 devs
2022-01-26 10:01:58.887 NOTICE: interface detected: tun0 (10.211.1.65)
2022-01-26 10:01:58.887 NOTICE: interface detected: eth0 (192.168.32.2)
2022-01-26 10:01:58.890 ERR: perr 10_show_dialog {}
2022-01-26 10:01:58.890 ERR: perr display {}
2022-01-26 10:01:58.890 NOTICE: run: E.update_consent(true)
2022-01-26 10:01:58.890 ERR: perr 15_choose_peer {}
2022-01-26 10:01:58.891 ERR: perr opt_in 
2022-01-26 10:01:58.892 NOTICE: perr lum_sdk_node_opt_in proxy 
2022-01-26 10:02:02.295 NOTICE: eth0 matched http://lumtest.com/myip.json
2022-01-26 10:02:02.295 NOTICE: dev eth0 connected
2022-01-26 10:02:02.296 NOTICE: device online: eth0, connecting...
2022-01-26 10:02:02.296 NOTICE: conn_open_single proxyjs.luminatinet.com:443 
2022-01-26 10:02:12.310 ERR: Error: queryA ETIMEOUT proxyjs.luminatinet.com
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:203:19)
2022-01-26 10:02:12.310 ERR: conn_open_single failed resolve proxyjs.luminatinet.com
2022-01-26 10:02:12.310 NOTICE: conn_open_single proxyjs.lum-sdk.io:443 
2022-01-26 10:02:22.323 ERR: Error: queryA ETIMEOUT proxyjs.lum-sdk.io
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:203:19)
2022-01-26 10:02:22.324 ERR: perr proxyjs_dns_failed {"host":"proxyjs.lum-sdk.io","port":443}
2022-01-26 10:02:22.324 NOTICE: perr lum_sdk_node_proxyjs_dns_failed proxy 
2022-01-26 10:02:22.326 ERR: conn_open_single failed resolve proxyjs.lum-sdk.io
2022-01-26 10:02:22.326 NOTICE: conn_open_single undefined:443 fallback_ip
2022-01-26 10:02:22.326 NOTICE: proxyjs_client_conn eth0 192.168.32.2 34.199.53.229:443(undefined) 
2022-01-26 10:02:22.327 NOTICE: proxy_eth0 WS: connecting to wss://34.199.53.229:443
2022-01-26 10:02:22.819 NOTICE: perr https://perr.l-err.biz/perr?id=lum_sdk_node_proxyjs_dns_failed&appid=node_earnapp.com&ver=1.272.126&ver_sdk=1.272.126&uuid=sdk-node-d430a58dd5944576809bb4023f11e4de res 200
2022-01-26 10:02:22.819 ERR: perr perr_direct_success {}
2022-01-26 10:02:22.822 ERR: proxy_eth0 WS: Hostname/IP does not match certificate's altnames: IP: 34.199.53.229 is not in the cert's list: 
2022-01-26 10:02:22.823 NOTICE: proxy disconnected
2022-01-26 10:02:23.824 NOTICE: conn_open_single p.l-conn.net:443 fallback_ip
2022-01-26 10:02:23.825 NOTICE: proxyjs_client_conn eth0 192.168.32.2 35.169.211.74:443(p.l-conn.net) 
2022-01-26 10:02:23.825 NOTICE: proxy_eth0 WS: connecting to wss://35.169.211.74:443
2022-01-26 10:02:24.248 ERR: Error: connect ECONNREFUSED 3.94.72.89:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
2022-01-26 10:02:24.249 ERR: perr err Error: connect ECONNREFUSED 104.248.48.136:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
2022-01-26 10:02:24.249 NOTICE: perr send failed: H perr.l-err.biz P  R undefined E Error: connect ECONNREFUSED 104.248.48.136:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
2022-01-26 10:02:24.249 NOTICE: perr lum_sdk_node_opt_in proxy 
2022-01-26 10:02:24.509 NOTICE: proxy_eth0 WS: upgrade conn
2022-01-26 10:02:24.510 NOTICE: proxy_eth0 WS (35.169.211.74): connected
2022-01-26 10:02:24.510 NOTICE: proxy connected
2022-01-26 10:02:24.510 ERR: perr proxyjs_conn_01_ip_success {"servername":"p.l-conn.net","port":443,"ip":"35.169.211.74"}
2022-01-26 10:02:24.511 NOTICE: perr lum_sdk_node_proxyjs_conn_01_ip_success proxy 
2022-01-26 10:02:24.514 ERR: perr 20_svc_connected {}
2022-01-26 10:02:24.514 ERR: perr connected {}
2022-01-26 10:02:24.515 NOTICE: detected interface eth0 for 192.168.32.2
2022-01-26 10:02:24.515 NOTICE: js peer init from 192.168.32.2 eth0 unknown
2022-01-26 10:02:24.515 NOTICE: tunnel_init resp: {"arch":"x64","release":"ubuntu_20.04_x64","platform":"node","sdk_version":"1.272.126","version":"1.272.126","idle":true,"confdir":"/etc/earnapp","old_cid":"hidden-95a831bf/hidden","dca":false,"is_tv":false,"appid":"node_earnapp.com","partnerid":"luminati","uuid":"sdk-node-d430a58dd5944576809bb4023f11e4de","ifname":"eth0","usage":{},"ifs":[{"name":"tun0","addr":"10.211.1.65"},{"name":"eth0","addr":"192.168.32.2"}]}
2022-01-26 10:02:24.691 NOTICE: tunnel_init_decline: ip_type.Data Center
2022-01-26 10:02:24.691 NOTICE: eth0 connect decline cooldown 86400000
2022-01-26 10:02:24.691 NOTICE: proxy_eth0 WS: ws.close
2022-01-26 10:02:24.692 NOTICE: proxy_eth0 WS (35.169.211.74): closed locally
2022-01-26 10:02:24.692 NOTICE: proxy disconnected
`

**Comment by Allaux** [comment]
And he will continus like this only connect to eth0 and if i have luck he connect to tun0

**Comment by Allaux** [comment]
This is my docker file :
version: "3.3"

volumes:
        earnapp_vpn: {}
services:
        app:
            image: fazalfarhan01/earnapp:lite
            volumes:
                - earnapp_vpn:/etc/earnapp
            environment:
                EARNAPP_UUID: sdk-node-

            network_mode: service:openvpn-client
            cap_add:
            - NET_ADMIN
            depends_on:
            - openvpn-client
            restart: unless-stopped
            command:
              - /bin/sh
              - -c
              - |
                  echo "sleep for 30sec"
                  sleep 30 
                  install
        openvpn-client:
            image: dperson/openvpn-client:latest
            container_name: openvpn-client
            cap_add:
            - NET_ADMIN
            devices:
            - /dev/net/tun
            volumes:
            - ./vpn:/vpn
            restart: unless-stopped

**Comment by fazalfarhan01** [comment]
You might want to route the traffic manually. Use `ip route show` to see the default route.
Then remove the default if it's via eth0. Add a default route via the tun0 gateway.

**Comment by Allaux** [comment]
![image](https://user-images.githubusercontent.com/86805606/151145186-4fd1bd6c-c478-4f53-b09d-e0c1cb2fb2bf.png)
i already use route del default eth0

**Comment by Allaux** [comment]
You think i need to add route add default tun0 ?

**Comment by fazalfarhan01** [comment]
> You think i need to add route add default tun0 ?


Nope. Seeing the snap you have attached. It should work. I don't see a reason why it wouldn't.
And if you haven't truncated a part of `ip route show` you'll need to add route to your VPN server IP via eth0

**Comment by Allaux** [comment]
No is not truncate maybe my vpn is work no problem is only earnapp to try eth0 and he use eth0 instead of tun0
Do you know how i can make for no show eth0 or replace eth0 by tun0 or other tricked for he work correctly

**Comment by fazalfarhan01** [comment]
Ping me on discord (toothyraider201#4454)
I might have a solution.

**Comment by Allaux** [comment]
I have send friend request on discord @fazalfarhan01

**Comment by molotovah** [comment]
@fazalfarhan01 : Hello, is this possible for you to add an OpenVPN config inside the docker ?
That would be great to be able to run it into differents containers.

**Comment by fazalfarhan01** [comment]
> Hello, is this possible for you to add an OpenVPN config inside the docker ?
> That would be great to be able to run it into differents containers. 

Although it could be possible, but I won't be adding it inside the container because it will increase the resources needed.
