### ISSUE TITLE
ARM64 executable is bugged again

### ISSUE THREAD

**Issue by idfxken** [fazalfarhan01/EarnApp-Docker#28]
on arm64, lite version:

An image by https://github.com/fazalfarhan01
Installing
internal/fs/utils.js:307
    throw err;
    ^
Error: ENOENT: no such file or directory, open '/usr/bin/node_modules/workerjs/bootstrap.js'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at Object.readFileSync (/usr/bin/earnapp:233:55)
    at Object.<anonymous> (/usr/bin/node_modules/workerjs/index.js:6:6)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/usr/bin/node_modules/workerjs/bootstrap.js'
}
internal/fs/utils.js:307
    throw err;
    ^
Error: ENOENT: no such file or directory, open '/usr/bin/node_modules/workerjs/bootstrap.js'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at Object.readFileSync (/usr/bin/earnapp:233:55)
    at Object.<anonymous> (/usr/bin/node_modules/workerjs/index.js:6:6)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/usr/bin/node_modules/workerjs/bootstrap.js'
}

**Comment by idfxken** [comment]
Update: on the regular earnapp version (aarch64) the same issue is happening after manually starting install, 
as the container just hangs otherwise

**Comment by fazalfarhan01** [comment]
@idfxken thanks for the issue. Earnapp has been having issues lately. This bug started a week ago and still being fixed. Their compiled image is missing a few dependencies 🥲 (ig they are trying to reduce the overall file size) 
For time being I'll roll back the updates and stop auto updating the image.

**Comment by fazalfarhan01** [comment]
@idfxken kindly pull the latest image. I have tested it and the executable seems fine.

**Comment by idfxken** [comment]
the same issue still persists, when run from a clean build environment, is it possible you forgot to delete the earnapp folder?

- stopped the broken container
- removed the earnapp folder
- docker system prune -a -f 

This is on 5 pi4 nodes, which were running fine, auto-updating, until about a week ago indeed. 
My (only) x86_64 node is doing fine with the auto updates somehow!

```
root@hermes:/srv/dockerconfigs# docker-compose  exec earnapp install

███████╗░█████╗░██████╗░███╗░░██╗░█████╗░██████╗░██████╗░  ██████╗░░█████╗░░█████╗░██╗░░██╗███████╗██████╗░
██╔════╝██╔══██╗██╔══██╗████╗░██║██╔══██╗██╔══██╗██╔══██╗  ██╔══██╗██╔══██╗██╔══██╗██║░██╔╝██╔════╝██╔══██╗
█████╗░░███████║██████╔╝██╔██╗██║███████║██████╔╝██████╔╝  ██║░░██║██║░░██║██║░░╚═╝█████═╝░█████╗░░██████╔╝
██╔══╝░░██╔══██║██╔══██╗██║╚████║██╔══██║██╔═══╝░██╔═══╝░  ██║░░██║██║░░██║██║░░██╗██╔═██╗░██╔══╝░░██╔══██╗
███████╗██║░░██║██║░░██║██║░╚███║██║░░██║██║░░░░░██║░░░░░  ██████╔╝╚█████╔╝╚█████╔╝██║░╚██╗███████╗██║░░██║
╚══════╝╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░╚══╝╚═╝░░╚═╝╚═╝░░░░░╚═╝░░░░░  ╚═════╝░░╚════╝░░╚════╝░╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝
An image by https://github.com/fazalfarhan01

Installing
internal/fs/utils.js:307
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/app/node_modules/workerjs/bootstrap.js'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at Object.readFileSync (/app/earnapp:233:55)
    at Object.<anonymous> (/app/node_modules/workerjs/index.js:6:6)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/app/node_modules/workerjs/bootstrap.js'
```

docker-compose config:
```
  earnapp:
    image: fazalfarhan01/earnapp:latest
    container_name: earnapp
    privileged: true
    volumes:
      - ./earnapp:/etc/earnapp
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    environment:
      EARNAPP_UUID: sdk-node-xxx
    restart: unless-stopped
```

**Comment by idfxken** [comment]
I'm trying the old images, to see where the lite version breaks, will update with the version where it breaks for aarch64
[lite-1.280.948] working
[lite-1.290.161] working
[lite-1.291.851] Broken

**Comment by fazalfarhan01** [comment]
> I'm trying the old images, to see where the lite version breaks, will update with the version where it breaks for aarch64

I did try both the `regular` and `lite` version on my RPi4 with latest 64bit Raspberry Pi OS... Everything seems to work on my side. New UUID is being generated, the device shows up as online on dashboard. Are you sure you are not using a cached image? I also have a **test before build** code that tests if the image is working fine. The latest images work fine.

**Comment by idfxken** [comment]
Ah, I am still running buster. 
As bullseye still has some open issues affecting my pi4 network.
But that shouldn't be an issue I believe?

**Comment by fazalfarhan01** [comment]
> But that shouldn't be an issue I believe?

Not at all..

**Comment by fazalfarhan01** [comment]
> I'm trying the old images, to see where the lite version breaks, will update with the version where it breaks for aarch64 
> [lite-1.280.948] working 
> [lite-1.290.161] working 
> [lite-1.291.851] Broken

I'll check this..

**Comment by fazalfarhan01** [comment]
@idfxken I can confirm the bug exists on the `arm64` images and the `amd64` images are working fine. 
Thanks for efforts. I have reported the earnapp staff regarding this on [Discord](https://discord.com/channels/894120260846891008/942085289340469299/961890221996277770)

**Comment by idfxken** [comment]
On x86_64 it runs perfectly indeed. I'll keep the arm64 on the previous version till I get more time. Thanks for the effort

**Comment by idfxken** [comment]
Just tested: 294.218  is working on the pi's. So this one can be closed :)
