### ISSUE TITLE
Impossible to start on docker / debian 11

### ISSUE THREAD

**Issue by dcjona** [fazalfarhan01/EarnApp-Docker#3]
Hi,
I got a problem trying to launch the docker compose or docker run
My container start and stop immediately.

I use the compose : 
version: "3.3"
services:
    app:
        image: fazalfarhan01/earnapp
        privileged: true
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
            - ./etc:/etc/earnapp
            
and then : 
dcjona@debian11:~/earnapp2$ sudo docker-compose up -d
Creating earnapp2_app_1 ... done

logs : 
No log line matching the '' filter

Do you have an idea? 

Thank you

**Comment by fazalfarhan01** [comment]
Debian uses cgroup version 1
The image uses version 2
They both are incompatible
And hence the issue
Use the lite version of the image, that doesn't need to be privileged and doesn't depend on cgroup

**Comment by dcjona** [comment]
ok thanks .. 

I use the lite for now but still at 0B so i'm asking if it works well here ..

**Comment by fazalfarhan01** [comment]
> ok thanks .. 
> 
> I use the lite for now but still at 0B so i'm asking if it works well here .. 
> 

Yep.. it's as good as the normal version, the only change is that the `earnapp install` command doesn't work because of inexistence of systemd. And so it won't generate its own UUID. Except that, it's the same thing

**Comment by dcjona** [comment]
ok so to get the id i need to install on windows and then take the id on the app right?

**Comment by fazalfarhan01** [comment]
> ok so to get the id i need to install on windows and then take the id on the app right? 

I don't think the windows IDs work. You need to install it using the official Linux script.. then copy the UUID into the container

**Comment by dcjona** [comment]
ok thanks

**Comment by dcjona** [comment]
i confirm it works with widonws too , size wa d0B anbd now after refresh 60Mo . 

Thanks for fast reply :D

**Comment by fazalfarhan01** [comment]
> i confirm it works with widonws too , size wa d0B anbd now after refresh 60Mo . 
> 
> Thanks for fast reply :D

The container works on windows but did you mean it works on windows UUIDs too?

**Comment by dcjona** [comment]
I try to install on windows yes , but wih the lite version i need to get the uuid and on windows i don't find them

**Comment by MrAuronTV** [comment]
i try to install lite version on WSL2, but how i can get earnapp uuid for environnement variable ?

**Comment by fazalfarhan01** [comment]
@dcjona You'll need to run the normal version on some other device.. get the UUID and then put it there.. 

Or [email me](mailto:fazal@ffehost.com) I'll send you a UUID which you can use.

**Comment by AvgAwsmDude** [comment]
@dcjona  i tried using lite version and when i ran the logs of the container i get this error ,


```
███████╗░█████╗░██████╗░███╗░░██╗░█████╗░██████╗░██████╗░  ██████╗░░█████╗░░█████╗░██╗░░██╗███████╗██████╗░
██╔════╝██╔══██╗██╔══██╗████╗░██║██╔══██╗██╔══██╗██╔══██╗  ██╔══██╗██╔══██╗██╔══██╗██║░██╔╝██╔════╝██╔══██╗
█████╗░░███████║██████╔╝██╔██╗██║███████║██████╔╝██████╔╝  ██║░░██║██║░░██║██║░░╚═╝█████═╝░█████╗░░██████╔╝
██╔══╝░░██╔══██║██╔══██╗██║╚████║██╔══██║██╔═══╝░██╔═══╝░  ██║░░██║██║░░██║██║░░██╗██╔═██╗░██╔══╝░░██╔══██╗
███████╗██║░░██║██║░░██║██║░╚███║██║░░██║██║░░░░░██║░░░░░  ██████╔╝╚█████╔╝╚█████╔╝██║░╚██╗███████╗██║░░██║
╚══════╝╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░╚══╝╚═╝░░╚═╝╚═╝░░░░░╚═╝░░░░░  ╚═════╝░░╚════╝░░╚════╝░╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝
An image by https://github.com/fazalfarhan01

Installing
printf: usage: printf [-v var] format [arguments]
- Checking IP...
earnapp start

Start making money in the background process

Options:
  --verbose  Run with extra logs                                       [boolean]
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]

Error: Request failed with status code 400
    at createError (/usr/bin/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/bin/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/bin/node_modules/axios/lib/adapters/http.js:293:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.22.0'
    },
    method: 'get',
    url: 'https://client.earnapp.com/is_ip_blocked',
    params: {
      uuid: '',
      version: '1.294.218',
      arch: 'x64',
      appid: 'node_earnapp.com'
    },
    data: undefined
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      socket: [Function (anonymous)],
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'client.earnapp.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'client.earnapp.com',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 13,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    _header: 'GET /is_ip_blocked?uuid=&version=1.294.218&arch=x64&appid=node_earnapp.com HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'User-Agent: axios/0.22.0\r\n' +
      'Host: client.earnapp.com\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'fifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/is_ip_blocked?uuid=&version=1.294.218&arch=x64&appid=node_earnapp.com',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 400,
      statusMessage: 'Bad Request',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://client.earnapp.com/is_ip_blocked?uuid=&version=1.294.218&arch=x64&appid=node_earnapp.com',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(RequestTimeout)]: undefined
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'client.earnapp.com',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://client.earnapp.com/is_ip_blocked?uuid=&version=1.294.218&arch=x64&appid=node_earnapp.com',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'user-agent': [Array],
      host: [Array]
    }
  },
  response: {
    status: 400,
    statusText: 'Bad Request',
    headers: {
      server: 'nginx',
      date: 'Wed, 11 May 2022 09:06:00 GMT',
      'content-type': 'text/html; charset=utf-8',
      'content-length': '17',
      connection: 'close',
      'cache-control': 'private,no-store'
    },
    config: {
      transitional: [Object],
      adapter: [Function: httpAdapter],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      headers: [Object],
      method: 'get',
      url: 'https://client.earnapp.com/is_ip_blocked',
      params: [Object],
      data: undefined
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'GET /is_ip_blocked?uuid=&version=1.294.218&arch=x64&appid=node_earnapp.com HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.22.0\r\n' +
        'Host: client.earnapp.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/is_ip_blocked?uuid=&version=1.294.218&arch=x64&appid=node_earnapp.com',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'client.earnapp.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: 'Invalid arguments'
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
2022-05-11 09:06:04.956 NOTICE: running PID: 24
2022-05-11 09:06:04.958 ERR: perr 05_svc_init {}
2022-05-11 09:06:04.960 NOTICE: perr lum_sdk_node_05_svc_init proxy 
2022-05-11 09:06:04.976 ERR: perr init {}
2022-05-11 09:06:04.977 NOTICE: perr lum_sdk_node_init proxy 
2022-05-11 09:06:04.979 NOTICE: idle_state_monitor run
2022-05-11 09:06:04.982 NOTICE: run: E.start()
2022-05-11 09:06:04.982 NOTICE: devs changed: found 1 devs
2022-05-11 09:06:04.982 NOTICE: interface detected: eth0 (172.17.0.2)
2022-05-11 09:06:04.984 ERR: perr 10_show_dialog {}
2022-05-11 09:06:04.984 NOTICE: perr lum_sdk_node_10_show_dialog proxy 
2022-05-11 09:06:04.985 ERR: perr display {}
2022-05-11 09:06:04.985 NOTICE: perr lum_sdk_node_display proxy 
2022-05-11 09:06:04.986 NOTICE: run: E.update_consent(true)
2022-05-11 09:06:04.986 ERR: perr 15_choose_peer {}
2022-05-11 09:06:04.987 NOTICE: perr lum_sdk_node_15_choose_peer proxy 
2022-05-11 09:06:04.987 ERR: perr opt_in 
2022-05-11 09:06:04.988 NOTICE: perr lum_sdk_node_opt_in proxy 
2022-05-11 09:06:05.516 NOTICE: eth0 matched http://lumtest.com/myip.json
2022-05-11 09:06:05.516 NOTICE: dev eth0 connected
2022-05-11 09:06:05.516 NOTICE: device online: eth0, connecting...
2022-05-11 09:06:05.517 NOTICE: conn_open_single proxyjs.luminatinet.com:443 
2022-05-11 09:06:05.580 NOTICE: proxyjs_client_conn eth0 172.17.0.2 54.227.144.19:443(proxyjs.luminatinet.com) 
2022-05-11 09:06:05.581 NOTICE: proxy_eth0 WS: connecting to wss://54.227.144.19:443
2022-05-11 09:06:05.751 NOTICE: perr https://perr.l-err.biz/perr?id=lum_sdk_node_10_show_dialog&appid=node_earnapp.com&ver=1.294.218&ver_sdk=1.294.218 res 200
2022-05-11 09:06:05.751 ERR: perr perr_direct_success {}
2022-05-11 09:06:05.752 NOTICE: perr lum_sdk_node_perr_direct_success proxy 
2022-05-11 09:06:05.779 NOTICE: perr https://perr.l-err.biz/perr?id=lum_sdk_node_display&appid=node_earnapp.com&ver=1.294.218&ver_sdk=1.294.218 res 200
2022-05-11 09:06:05.781 ERR: ndt7 get config error: Request failed with status code 400
2022-05-11 09:06:05.802 NOTICE: perr https://perr.l-err.biz/perr?id=lum_sdk_node_opt_in&appid=node_earnapp.com&ver=1.294.218&ver_sdk=1.294.218 res 200
2022-05-11 09:06:05.818 NOTICE: perr https://perr.l-err.biz/perr?id=lum_sdk_node_init&appid=node_earnapp.com&ver=1.294.218&ver_sdk=1.294.218 res 200
2022-05-11 09:06:05.854 NOTICE: perr https://perr.l-err.biz/perr?id=lum_sdk_node_05_svc_init&appid=node_earnapp.com&ver=1.294.218&ver_sdk=1.294.218 res 200
2022-05-11 09:06:05.895 NOTICE: perr https://perr.l-err.biz/perr?id=lum_sdk_node_15_choose_peer&appid=node_earnapp.com&ver=1.294.218&ver_sdk=1.294.218 res 200
2022-05-11 09:06:06.588 NOTICE: perr https://perr.l-err.biz/perr?id=lum_sdk_node_perr_direct_success&appid=node_earnapp.com&ver=1.294.218&ver_sdk=1.294.218 res 200
2022-05-11 09:06:06.705 NOTICE: proxy_eth0 WS: upgrade conn
2022-05-11 09:06:06.706 NOTICE: proxy_eth0 WS (54.227.144.19): connected
2022-05-11 09:06:06.706 NOTICE: proxy connected
2022-05-11 09:06:06.706 ERR: perr proxyjs_conn_00_direct_success {"servername":"proxyjs.luminatinet.com","port":443,"ip":"54.227.144.19"}
2022-05-11 09:06:06.706 NOTICE: perr lum_sdk_node_proxyjs_conn_00_direct_success proxy 
2022-05-11 09:06:06.708 ERR: perr 20_svc_connected {}
2022-05-11 09:06:06.709 NOTICE: perr lum_sdk_node_20_svc_connected proxy 
2022-05-11 09:06:06.709 ERR: perr connected {}
2022-05-11 09:06:06.710 NOTICE: perr lum_sdk_node_connected proxy 
2022-05-11 09:06:06.710 NOTICE: detected interface eth0 for 172.17.0.2
2022-05-11 09:06:06.710 NOTICE: js peer init from 172.17.0.2 eth0 unknown
2022-05-11 09:06:06.711 NOTICE: tunnel_init resp: {"arch":"x64","release":"ubuntu_20.04_x64","platform":"node","sdk_version":"1.294.218","version":"1.294.218","idle":true,"confdir":"/etc/earnapp","old_cid":null,"dca":false,"is_tv":false,"appid":"node_earnapp.com","partnerid":"luminati","ifname":"eth0","usage":{},"ifs":[{"name":"eth0","addr":"172.17.0.2"}]}
2022-05-11 09:06:07.081 NOTICE: eth0 cid_set 122.167.13.72-7fd20c50/ls7c7p443_122.167.13.72_50780
            session_key undefined
2022-05-11 09:06:07.081 ERR: perr register_client {"msg":"ls7c7p443_122.167.13.72_50780","body":"{\"type\":\"eth0\",\"myip\":\"{\\\"ip\\\":\\\"122.167.13.72\\\",\\\"country\\\":\\\"IN\\\",\\\"asn\\\":{\\\"asnum\\\":24560,\\\"org_name\\\":\\\"Bharti Airtel Ltd., Telemedia Services\\\"},\\\"geo\\\":{\\\"city\\\":\\\"Bengaluru\\\",\\\"region\\\":\\\"KA\\\",\\\"region_name\\\":\\\"Karnataka\\\",\\\"postal_code\\\":\\\"560002\\\",\\\"latitude\\\":12.9634,\\\"longitude\\\":77.5855,\\\"tz\\\":\\\"Asia/Kolkata\\\",\\\"lum_city\\\":\\\"bengaluru\\\",\\\"lum_region\\\":\\\"ka\\\"}}\"}"}
2022-05-11 09:06:07.081 NOTICE: perr lum_sdk_node_register_client proxy 
2022-05-11 09:06:07.084 NOTICE: status_get: {"idle":true,"usage":{},"idle_state":{"mem_usage":34.46,"mem_usage_ts":1652259965064,"cpu_usage":7.69,"cpu_usage_ts":1652259965980},"bw":{}}
2022-05-11 09:06:07.381 ERR: perr 21_svc_tun_ready {}
2022-05-11 09:06:07.382 NOTICE: perr lum_sdk_node_21_svc_tun_ready proxy 
2022-05-11 09:06:07.383 ERR: perr tun_ready {}
2022-05-11 09:06:07.383 NOTICE: perr lum_sdk_node_tun_ready proxy 
2022-05-11 09:06:07.386 NOTICE: client_connect start [172.17.0.2]->64.227.179.8:443 (64-227-179-8.luminatinet.com)
2022-05-11 09:06:07.386 NOTICE: agent WS: connecting to wss://64.227.179.8:443
2022-05-11 09:06:07.390 ERR: perr 21_svc_tun_ready {}
2022-05-11 09:06:07.390 ERR: perr tun_ready {}
2022-05-11 09:06:07.390 NOTICE: client_connect start [172.17.0.2]->104.248.152.57:443 (104-248-152-57.luminatinet.com)
2022-05-11 09:06:07.391 NOTICE: agent WS: connecting to wss://104.248.152.57:443
2022-05-11 09:06:07.394 ERR: perr 21_svc_tun_ready {}
2022-05-11 09:06:07.394 ERR: perr tun_ready {}
2022-05-11 09:06:07.395 NOTICE: client_connect start [172.17.0.2]->178.128.126.15:443 (178-128-126-15.luminatinet.com)
2022-05-11 09:06:07.395 NOTICE: agent WS: connecting to wss://178.128.126.15:443
2022-05-11 09:06:07.558 NOTICE: perr https://perr.l-err.biz/perr?id=lum_sdk_node_20_svc_connected&appid=node_earnapp.com&ver=1.294.218&ver_sdk=1.294.218 res 200
2022-05-11 09:06:07.600 NOTICE: agent WS: upgrade conn
2022-05-11 09:06:07.601 NOTICE: agent WS (64.227.179.8): connected
2022-05-11 09:06:07.601 NOTICE: client_connect established [172.17.0.2]->64.227.179.8:443 (64-227-179-8.luminatinet.com)
2022-05-11 09:06:07.601 ERR: perr tun_init_success {"servername":"64-227-179-8.luminatinet.com"}
2022-05-11 09:06:07.602 NOTICE: perr lum_sdk_node_tun_init_success proxy 
2022-05-11 09:06:07.603 NOTICE: detected interface eth0 for 172.17.0.2
2022-05-11 09:06:07.604 NOTICE: js peer init from 172.17.0.2 eth0 unknown
2022-05-11 09:06:07.604 NOTICE: tunnel_init resp: {"arch":"x64","release":"ubuntu_20.04_x64","platform":"node","sdk_version":"1.294.218","version":"1.294.218","idle":true,"confdir":"/etc/earnapp","cid":"122.167.13.72-7fd20c50/ls7c7p443_122.167.13.72_50780","old_cid":"122.167.13.72-7fd20c50/ls7c7p443_122.167.13.72_50780","dca":false,"is_tv":false,"appid":"node_earnapp.com","partnerid":"luminati","ifname":"eth0","usage":{},"ifs":[{"name":"eth0","addr":"172.17.0.2"}]}
2022-05-11 09:06:07.612 NOTICE: agent WS: upgrade conn
2022-05-11 09:06:07.612 NOTICE: agent WS (104.248.152.57): connected
2022-05-11 09:06:07.613 NOTICE: client_connect established [172.17.0.2]->104.248.152.57:443 (104-248-152-57.luminatinet.com)
2022-05-11 09:06:07.613 ERR: perr tun_init_success {"servername":"104-248-152-57.luminatinet.com"}
2022-05-11 09:06:07.613 NOTICE: detected interface eth0 for 172.17.0.2
2022-05-11 09:06:07.613 NOTICE: js peer init from 172.17.0.2 eth0 unknown
2022-05-11 09:06:07.614 NOTICE: tunnel_init resp: {"arch":"x64","release":"ubuntu_20.04_x64","platform":"node","sdk_version":"1.294.218","version":"1.294.218","idle":true,"confdir":"/etc/earnapp","cid":"122.167.13.72-7fd20c50/ls7c7p443_122.167.13.72_50780","old_cid":"122.167.13.72-7fd20c50/ls7c7p443_122.167.13.72_50780","dca":false,"is_tv":false,"appid":"node_earnapp.com","partnerid":"luminati","ifname":"eth0","usage":{},"ifs":[{"name":"eth0","addr":"172.17.0.2"}]}
2022-05-11 09:06:07.632 NOTICE: perr https://perr.l-err.biz/perr?id=lum_sdk_node_connected&appid=node_earnapp.com&ver=1.294.218&ver_sdk=1.294.218 res 200
2022-05-11 09:06:07.642 NOTICE: status_get: {"idle":true,"usage":{},"idle_state":{"mem_usage":34.46,"mem_usage_ts":1652259965064,"cpu_usage":7.69,"cpu_usage_ts":1652259965980},"bw":{}}
2022-05-11 09:06:07.664 NOTICE: agent WS: upgrade conn
2022-05-11 09:06:07.664 NOTICE: agent WS (178.128.126.15): connected
2022-05-11 09:06:07.664 NOTICE: client_connect established [172.17.0.2]->178.128.126.15:443 (178-128-126-15.luminatinet.com)
2022-05-11 09:06:07.665 ERR: perr tun_init_success {"servername":"178-128-126-15.luminatinet.com"}
2022-05-11 09:06:07.665 NOTICE: detected interface eth0 for 172.17.0.2
2022-05-11 09:06:07.665 NOTICE: js peer init from 172.17.0.2 eth0 unknown
2022-05-11 09:06:07.666 NOTICE: tunnel_init resp: {"arch":"x64","release":"ubuntu_20.04_x64","platform":"node","sdk_version":"1.294.218","version":"1.294.218","idle":true,"confdir":"/etc/earnapp","cid":"122.167.13.72-7fd20c50/ls7c7p443_122.167.13.72_50780","old_cid":"122.167.13.72-7fd20c50/ls7c7p443_122.167.13.72_50780","dca":false,"is_tv":false,"appid":"node_earnapp.com","partnerid":"luminati","ifname":"eth0","usage":{},"ifs":[{"name":"eth0","addr":"172.17.0.2"}]}
2022-05-11 09:06:07.666 NOTICE: status_get: {"idle":true,"usage":{},"idle_state":{"mem_usage":34.46,"mem_usage_ts":1652259965064,"cpu_usage":7.69,"cpu_usage_ts":1652259965980},"bw":{}}
2022-05-11 09:06:07.718 NOTICE: status_get: {"idle":true,"usage":{},"idle_state":{"mem_usage":34.46,"mem_usage_ts":1652259965064,"cpu_usage":7.69,"cpu_usage_ts":1652259965980},"bw":{}}
2022-05-11 09:06:07.720 NOTICE: perr https://perr.l-err.biz/perr?id=lum_sdk_node_proxyjs_conn_00_direct_success&appid=node_earnapp.com&ver=1.294.218&ver_sdk=1.294.218 res 200
2022-05-11 09:06:07.895 NOTICE: perr https://perr.l-err.biz/perr?id=lum_sdk_node_register_client&appid=node_earnapp.com&ver=1.294.218&ver_sdk=1.294.218 res 200
2022-05-11 09:06:08.152 NOTICE: perr https://perr.l-err.biz/perr?id=lum_sdk_node_21_svc_tun_ready&appid=node_earnapp.com&ver=1.294.218&ver_sdk=1.294.218 res 200
2022-05-11 09:06:08.250 NOTICE: perr https://perr.l-err.biz/perr?id=lum_sdk_node_tun_ready&appid=node_earnapp.com&ver=1.294.218&ver_sdk=1.294.218 res 200
2022-05-11 09:06:08.350 NOTICE: perr https://perr.l-err.biz/perr?id=lum_sdk_node_tun_init_success&appid=node_earnapp.com&ver=1.294.218&ver_sdk=1.294.218 res 200
2022-05-11 09:06:12.337 ERR: perr 21_svc_tun_start {}
2022-05-11 09:06:12.338 NOTICE: perr lum_sdk_node_21_svc_tun_start proxy 
2022-05-11 09:06:12.339 ERR: perr tun_start {}
2022-05-11 09:06:12.339 NOTICE: perr lum_sdk_node_tun_start proxy 
2022-05-11 09:06:12.340 NOTICE: cmd_tun 64.227.179.8:443 
2022-05-11 09:06:12.357 ERR: perr 22_svc_tun_1b {}
2022-05-11 09:06:12.357 NOTICE: perr lum_sdk_node_22_svc_tun_1b proxy 
2022-05-11 09:06:12.358 ERR: perr tun_1b {}
2022-05-11 09:06:12.358 NOTICE: perr lum_sdk_node_tun_1b proxy 
2022-05-11 09:06:13.076 NOTICE: perr https://perr.l-err.biz/perr?id=lum_sdk_node_21_svc_tun_start&appid=node_earnapp.com&ver=1.294.218&ver_sdk=1.294.218 res 200
2022-05-11 09:06:13.090 NOTICE: perr https://perr.l-err.biz/perr?id=lum_sdk_node_22_svc_tun_1b&appid=node_earnapp.com&ver=1.294.218&ver_sdk=1.294.218 res 200
2022-05-11 09:06:13.098 NOTICE: perr https://perr.l-err.biz/perr?id=lum_sdk_node_tun_1b&appid=node_earnapp.com&ver=1.294.218&ver_sdk=1.294.218 res 200
2022-05-11 09:06:13.099 NOTICE: perr https://perr.l-err.biz/perr?id=lum_sdk_node_tun_start&appid=node_earnapp.com&ver=1.294.218&ver_sdk=1.294.218 res 200
2022-05-11 09:06:14.971 NOTICE: cmd_tun_close 1 
2022-05-11 09:06:16.546 ERR: ndt7 get config error: Request failed with status code 400
2022-05-11 09:06:22.401 WARN: agent WS (64.227.179.8): zfin_pending: 1-timeout
2022-05-11 09:06:27.242 ERR: ndt7 get config error: Request failed with status code 400

```


im using ubuntu 20 version , any idea what am i doing wrong? when i try non-lite version the contaainer keeps exiting so i tried lite version
